=== jedomor/MARCAS-06-XML/MARCAS validacion XML/dtd_ejercicio_4.dtd
<!ELEMENT matricula (personal,pago)>
<!ELEMENT personal (dni,nombre,titulacion,curso_academico,domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio+)>
<!ELEMENT domicilio (nombre)>
<!ELEMENT pago (tipo_matricula,tipo_pago)>
<!ELEMENT tipo_matricula (#PCDATA)>
<!ELEMENT tipo_pago (efectivo|transferencia|tarjeta)>
<!ELEMENT efectivo EMPTY>
<!ELEMENT transferencia EMPTY>
<!ELEMENT tarjeta EMPTY>

=== jedomor/MARCAS-06-XML/MARCAS validacion XML/dtd_ejercicio_4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE matricula SYSTEM "dtd_ejercicio_4.dtd">
<matricula>
    <personal>
        <dni>99223366M</dni>
        <nombre>Juan Pardo Martín</nombre>
        <titulacion>Ingeniería Informática</titulacion>
        <curso_academico>2020/2021</curso_academico>
        <domicilios>
            <domicilio>
                <nombre>C/ Principal nº1</nombre>
            </domicilio>
            <domicilio>
                <nombre>C/ Secundaria nº2</nombre>
            </domicilio>
        </domicilios>
    </personal>
    <pago>
        <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
        <tipo_pago>
            <efectivo />
        </tipo_pago>
    </pago>
</matricula>
