=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_ejercicio_5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modelo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id_modelo" type="xs:string" />
                            <xs:element name="precio" type="xs:decimal" />
                            <xs:element name="tallas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="small" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="color" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="medium" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="color" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="large" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="color" maxOccurs="unbounded"
                                                        type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="opiniones" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="opinion" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_ejercicio_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_ejercicio_5.xsd">
    <modelo>
        <id_modelo>QWZ5671</id_modelo>
        <precio>39.95</precio>
        <tallas>
            <medium>
                <color>Red</color>
                <color>Blue</color>
            </medium>
            <large>
                <color>Red</color>
                <color>Burgundy</color>
            </large>
        </tallas>
    </modelo>
    <opiniones>
        <opinion>Muy ponible en cualquier situaci√≥n</opinion>
    </opiniones>
</catalogo>
