=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_ejercicio_12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="tipo_codigo">
        <xs:restriction base="xs:integer">
            <xs:totalDigits value="6"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_cod_postal" >
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_importe">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="8"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_cif">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_cantidad">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_forma_pago">
        <xs:restriction base="xs:string" >
            <xs:enumeration value="efectivo"/>
            <xs:enumeration value="tarjeta"/>
            <xs:enumeration value="transferencia"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="tipo_moneda">
        <xs:restriction base="xs:string">
            <xs:enumeration value="dolar"/>
            <xs:enumeration value="euro"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datos_empresa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="dir" type="xs:string" />
                            <xs:element name="cod_postal" type="tipo_cod_postal" />
                            <xs:element name="poblacion" type="xs:string" />
                            <xs:element name="provincia" type="xs:string" />
                            <xs:element name="cif" type="tipo_cif" />
                            <xs:element name="telefono" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_cliente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="dir_env" type="xs:string" />
                            <xs:element name="cod_postal" type="xs:string" />
                            <xs:element name="poblacion" type="xs:string" />
                            <xs:element name="provincia" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="cod_cli" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="datos_factura">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fecha" type="xs:string" />
                            <xs:element name="linea" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ref" type="xs:string" />
                                        <xs:element name="desc" type="xs:string" />
                                        <xs:element name="cant" type="tipo_cantidad" />
                                        <xs:element name="precio" type="xs:string" />
                                        <xs:element name="subtotal" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="base" type="xs:string" />
                            <xs:element name="cuota_iva" type="xs:string" />
                            <xs:element name="total" type="tipo_importe" />
                        </xs:sequence>
                        <xs:attribute name="cod_ped" type="xs:integer" use="required" />
                        <xs:attribute name="iva" type="xs:integer" use="required" />
                        <xs:attribute name="forma_pago" type="tipo_forma_pago" use="required" />
                        <xs:attribute name="moneda" type="tipo_moneda" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="cod_fac" type="tipo_codigo" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_ejercicio_12.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="xsd_ejercicio_12.xsd" cod_fac="999">
    <datos_empresa>
        <nombre>Equipos Digitales S.L.</nombre>
        <dir>Av. Valladolid</dir>
        <cod_postal>28043</cod_postal>
        <poblacion>Madrid</poblacion>
        <provincia>Madrid</provincia>
        <cif>Q98765433</cif>
        <telefono />
    </datos_empresa>
    <datos_cliente cod_cli="879">
        <nombre>Darío Bueno Gutiérrez</nombre>
        <dir_env>Av. Oporto nº7 4ºd</dir_env>
        <cod_postal>28043</cod_postal>
        <poblacion>Madrid</poblacion>
        <provincia>Madrid</provincia>
    </datos_cliente>
    <datos_factura cod_ped="731" iva="21" forma_pago="efectivo" moneda="euro">
        <fecha>2005-12-01</fecha>
        <linea>
            <ref>MII93000F/8</ref>
            <desc>MICRO PENTIUM IV 3000MHZ FB800</desc>
            <cant>1</cant>
            <precio>230</precio>
            <subtotal>230</subtotal>
        </linea>
        <linea>
            <ref>MB8QDIP4</ref>
            <desc>PLACA BASE QDI P4</desc>
            <cant>1</cant>
            <precio>208.80</precio>
            <subtotal>208.80</subtotal>
        </linea>
        <linea>
            <ref>MEDD512M32</ref>
            <desc>DIMM DDR 512MB 3200</desc>
            <cant>2</cant>
            <precio>40</precio>
            <subtotal>80</subtotal>
        </linea>
        <linea>
            <ref>HD250GSA7</ref>
            <desc>DISCO DURO 250GB S-ATA 7200</desc>
            <cant>4</cant>
            <precio>60.10</precio>
            <subtotal>240.40</subtotal>
        </linea>
        <base>759.2</base>
        <cuota_iva>159.43</cuota_iva>
        <total>918.63</total>
    </datos_factura>
</factura>
