=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_Ejercicio_7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="html">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="head" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body" minOccurs="0">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="h1" type="xs:string" />
                            <xs:element name="h2" type="xs:string" />
                            <xs:element name="p">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="br" minOccurs="0" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_Ejercicio_7.xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_Ejercicio_7.xsd">
    <head>
        <title>Canal Marcas</title>
    </head>
    <body>
        <h1>¿Es ético falsificar conversaciones de Whatsapp?</h1>
        <h2>...solo para gastar una broma inofensiva</h2>
        <p>Se dice que el superpoder de la invisibilidad solo puede usarse para hacer el mal.
            Esconderse no tiene una utilidad heroica y solo sirve para espiar y engañar. Engañar es
            precisamente lo que hace la aplicación que hoy traemos a este espacio. Con ella puedes
            falsificar conversaciones de WhatsApp. <br /> ¿Hasta qué punto es ética? <br /> ¿Cómo se
            justifica su existencia?</p>
    </body>
</html>
