=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_ejercicio_6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="matriculacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="curso_academico" type="xs:string" />
                <xs:element name="matricula">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datos_personales">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dni" type="xs:string" />
                                        <xs:element name="nombre" type="xs:string" />
                                        <xs:element name="titulacion" type="xs:string" />
                                        <xs:element name="domicilios">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="domicilio"
                                                        maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="nombre"
                                                                    type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="pago">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo_matricula" type="xs:string" />
                                        <xs:element name="fecha_pago" type="xs:string" />
                                        <xs:element name="tipo_pago">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="efectivo" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jedomor/MARCAS-06-XML/MARCAS validacion XML/xsd_ejercicio_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<matriculacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="xsd_ejercicio_6.xsd">
    <curso_academico>2020/2021</curso_academico>
    <matricula>
        <datos_personales>
            <dni>99223366M</dni>
            <nombre>Juan Pardo Martín</nombre>
            <titulacion>Ingeniería Informática</titulacion>
            <domicilios>
                <domicilio>
                    <nombre>C/ Principal nº1</nombre>
                </domicilio>
                <domicilio>
                    <nombre>C/ Secundaria nº2</nombre>
                </domicilio>
            </domicilios>
        </datos_personales>
        <pago>
            <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
            <fecha_pago>2021-01-24</fecha_pago>
            <tipo_pago>
                <efectivo>648.12</efectivo>
            </tipo_pago>
        </pago>
    </matricula>
</matriculacion>
